# This is a basic workflow to help you get started with Actions

name: clean workflow

# Controls when the action will run. 
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  job_one:
    name: Clean
    runs-on: ubuntu-latest
    steps:
      - name: testing
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST}}
          username:  ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            unalias rm
            rm -rf cmsc388T-we-template
