# This is a basic workflow to help you get started with Actions

name: clone workflow

# Controls when the action will run. 
on:
  workflow_dispatch: https://terpconnect.umd.edu/~rogerluo/cmsc388T-web-template/

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  job_one:
    name: Clone
    runs-on: ubuntu-latest
    steps:
      - name: testing
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST}}
          username:  ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            git clone https://github.com/rogerluo-zyz/cmsc388T-web-template.git
